#!/usr/bin/env python3
"""Interactive local dashboard — opens as a standalone app window.

Serves the live E-Bike Hunter dashboard (view, reject, mark sold, correct
specs by hand) on localhost and launches it in a Chromium-based browser's
"app mode" window (no address bar or tabs — looks like a real program)
instead of an ordinary browser tab. Falls back to your default browser if
no Chromium-based browser is found.

Unlike index.html (a static snapshot regenerated by run.py/analyze.py after
each scan), this reads the DB live on every page load and writes back to it
immediately when you click a button — no regeneration step needed.

Run: python3 server.py
Stop: Ctrl+C in this terminal (closing the app window alone does not stop
the server, since a plain browser window can't signal that back).
"""
import shutil
import subprocess
import sys
import threading
import time
import webbrowser
from pathlib import Path
from typing import Optional
from urllib.parse import urlsplit

BASE_DIR = Path(__file__).parent
sys.path.insert(0, str(BASE_DIR / "src"))

from flask import Flask, abort, jsonify, request

from db.database import Database
from pipeline.corrections import apply_spec_correction
from pipeline.scoring import ScoringEngine
from scripts.generate_dashboard import render_dashboard_html
from utils.config import load_config

HOST = "127.0.0.1"
PORT = 5050
URL = f"http://{HOST}:{PORT}"


config = load_config()
DATABASE_URL = config["app"]["database_url"]
scorer = ScoringEngine(config)

app = Flask(__name__)

# Hostnames this local server answers to. Anything else in the Host header is
# a DNS-rebinding attempt (a public name pointed at 127.0.0.1).
_ALLOWED_HOSTNAMES = {"127.0.0.1", "localhost"}


def _hostname(value: str) -> str:
    """'localhost:5050' -> 'localhost', 'http://127.0.0.1:5050' -> '127.0.0.1'."""
    netloc = urlsplit(value).netloc if "://" in value else value
    return netloc.rsplit(":", 1)[0].strip("[]").lower()


@app.before_request
def _block_cross_site_requests():
    """Every other website open in the same browser can send requests to
    http://127.0.0.1:5050 — without this, any page could POST to /delete or
    /specs (get_json(force=True) even accepts a text/plain body, which needs
    no CORS preflight). Browsers always attach Origin to cross-origin POSTs,
    and Sec-Fetch-Site on modern ones; the dashboard's own fetch() calls are
    same-origin and pass."""
    if _hostname(request.host or "") not in _ALLOWED_HOSTNAMES:
        abort(403)
    if request.method in ("GET", "HEAD", "OPTIONS"):
        return None
    if request.headers.get("Sec-Fetch-Site") == "cross-site":
        abort(403)
    origin = request.headers.get("Origin")
    if origin is not None and _hostname(origin) not in _ALLOWED_HOSTNAMES:
        abort(403)
    return None


@app.route("/")
def index():
    return render_dashboard_html(DATABASE_URL, interactive=True)


@app.route("/api/listings/<listing_id>/reject", methods=["POST"])
def reject(listing_id):
    try:
        with Database(DATABASE_URL) as db:
            db.set_manual_status(listing_id, "REJECTED")
        return jsonify({"ok": True})
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    except Exception as e:
        import logging
        logging.error(f"Error rejecting listing {listing_id}: {e}")
        return jsonify({"error": "Failed to reject listing"}), 500


@app.route("/api/listings/<listing_id>/sold", methods=["POST"])
def sold(listing_id):
    try:
        with Database(DATABASE_URL) as db:
            db.set_manual_status(listing_id, "SOLD")
        return jsonify({"ok": True})
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    except Exception as e:
        import logging
        logging.error(f"Error marking listing {listing_id} sold: {e}")
        return jsonify({"error": "Failed to mark as sold"}), 500


@app.route("/api/listings/<listing_id>/restore", methods=["POST"])
def restore(listing_id):
    try:
        with Database(DATABASE_URL) as db:
            db.set_manual_status(listing_id, "ACTIVE")
        return jsonify({"ok": True})
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    except Exception as e:
        import logging
        logging.error(f"Error restoring listing {listing_id}: {e}")
        return jsonify({"error": "Failed to restore listing"}), 500


@app.route("/api/listings/<listing_id>/delete", methods=["POST"])
def delete_listing(listing_id):
    try:
        with Database(DATABASE_URL) as db:
            db.delete_listing(listing_id)
        return jsonify({"ok": True})
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    except Exception as e:
        import logging
        logging.error(f"Error deleting listing {listing_id}: {e}")
        return jsonify({"error": "Failed to delete listing"}), 500


@app.route("/api/listings/<listing_id>/favorite", methods=["POST"])
def favorite(listing_id):
    try:
        with Database(DATABASE_URL) as db:
            new_value = db.toggle_favorite(listing_id)
        return jsonify({"ok": True, "is_favorite": new_value})
    except ValueError:
        return jsonify({"error": "listing not found"}), 404
    except Exception as e:
        import logging
        logging.error(f"Error toggling favorite for listing {listing_id}: {e}")
        return jsonify({"error": "Failed to toggle favorite"}), 500


@app.route("/api/listings/<listing_id>/specs", methods=["POST"])
def update_specs(listing_id):
    try:
        data = request.get_json(force=True, silent=True) or {}
        with Database(DATABASE_URL) as db:
            score_result = apply_spec_correction(db, scorer, listing_id, data, config=config)

        if score_result is None:
            return jsonify({"error": "listing not found or no editable fields given"}), 404

        return jsonify({"ok": True, "score_total": score_result["score_total"]})
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    except Exception as e:
        import logging
        logging.error(f"Error updating specs for listing {listing_id}: {e}")
        return jsonify({"error": "Failed to update specifications"}), 500


@app.route("/api/top-deals", methods=["GET"])
def get_top_deals_dynamic():
    try:
        filters = {
            'price_min': request.args.get('price_min', type=float),
            'price_max': request.args.get('price_max', type=float),
            'dist_max': request.args.get('dist_max', type=float),
            'motor_brand': request.args.get('motor_brand'),
            'battery_min': request.args.get('battery_min', type=float),
            'frame_size': request.args.get('frame_size'),
            'year_min': request.args.get('year_min', type=int),
            'year_max': request.args.get('year_max', type=int),
            'score_min': request.args.get('score_min', default=60.0, type=float),
            'status': request.args.get('status'),
            'fav_only': request.args.get('fav_only', default=False, type=lambda x: x.lower() == 'true'),
            'ai_only': request.args.get('ai_only', default=False, type=lambda x: x.lower() == 'true'),
            'show_rejected': request.args.get('show_rejected', default=False, type=lambda x: x.lower() == 'true'),
            'limit': min(request.args.get('limit', default=10, type=int), 1000),  # Cap at 1000
        }

        filters = {k: (v if v != 'undefined' else None) for k, v in filters.items()}

        with Database(DATABASE_URL) as db:
            deals = db.get_filtered_top_deals(**filters)

        return jsonify([dict(deal) for deal in deals])
    except Exception as e:
        import logging
        logging.error(f"Error fetching deals with filters {filters}: {e}")
        return jsonify({"error": "Failed to fetch deals"}), 500


def _find_app_mode_browser() -> Optional[str]:
    """Find a Chromium-based browser that supports --app= (a borderless
    window with no tabs/address bar — the closest a plain web page gets to
    looking like a real desktop program), checked in the order a Mac user
    is likely to have them installed."""
    candidates = [
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
        "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser",
        "/Applications/Chromium.app/Contents/MacOS/Chromium",
        shutil.which("google-chrome"),
        shutil.which("chromium"),
        shutil.which("chromium-browser"),
        shutil.which("microsoft-edge"),
    ]
    for path in candidates:
        if path and Path(path).exists():
            return path
    return None


def _app_profile_dir() -> Path:
    if sys.platform == "darwin":
        return Path.home() / "Library" / "Application Support" / "EbikeHunterAppMode"
    if sys.platform.startswith("win"):
        return Path.home() / "AppData" / "Local" / "EbikeHunterAppMode"
    return Path.home() / ".config" / "EbikeHunterAppMode"


APP_PROFILE_DIR = _app_profile_dir()


def _open_app_window():
    time.sleep(0.8)  # give the Flask server a moment to start listening
    browser = _find_app_mode_browser()
    if browser:
        # A dedicated profile dir — never the user's real Chrome profile —
        # so this doesn't touch (or fight over) that profile's SingletonLock
        # when the user's own Chrome isn't already running.
        subprocess.Popen([
            browser,
            f"--app={URL}",
            "--window-size=1400,900",
            f"--user-data-dir={APP_PROFILE_DIR}",
        ])
    else:
        print("Nessun browser Chromium-based trovato per la modalità app — apro nel browser predefinito.")
        webbrowser.open(URL)


if __name__ == "__main__":
    print("E-Bike Hunter — dashboard interattiva")
    print(f"Apro {URL} in una finestra app (Ctrl+C qui per fermare il server)")
    threading.Thread(target=_open_app_window, daemon=True).start()
    app.run(host=HOST, port=PORT, debug=False)
