#!/usr/bin/env python3
"""Interactive local dashboard — opens as a standalone app window.

Serves the live E-Bike Hunter dashboard (view, reject, mark sold, correct
specs by hand) on localhost and launches it in a Chromium-based browser's
"app mode" window (no address bar or tabs — looks like a real program)
instead of an ordinary browser tab. Falls back to your default browser if
no Chromium-based browser is found.

Unlike index.html (a static snapshot regenerated by run.py/analyze.py after
each scan), this reads the DB live on every page load and writes back to it
immediately when you click a button — no regeneration step needed.

Run: python3 server.py
Stop: Ctrl+C in this terminal (closing the app window alone does not stop
the server, since a plain browser window can't signal that back).
"""
import shutil
import subprocess
import sys
import threading
import time
import webbrowser
from pathlib import Path
from typing import Optional

BASE_DIR = Path(__file__).parent
sys.path.insert(0, str(BASE_DIR / "src"))

import yaml
from flask import Flask, jsonify, request

from db.database import Database
from pipeline.corrections import apply_spec_correction
from pipeline.scoring import ScoringEngine
from scripts.generate_dashboard import render_dashboard_html

HOST = "127.0.0.1"
PORT = 5050
URL = f"http://{HOST}:{PORT}"


def load_config():
    with open(BASE_DIR / "config" / "config.yaml") as f:
        return yaml.safe_load(f)


config = load_config()
DB_PATH = config["app"]["db_path"]
scorer = ScoringEngine(config)

app = Flask(__name__)


@app.route("/")
def index():
    return render_dashboard_html(DB_PATH, interactive=True)


@app.route("/api/listings/<listing_id>/reject", methods=["POST"])
def reject(listing_id):
    db = Database(DB_PATH)
    db.set_manual_status(listing_id, "REJECTED")
    db.close()
    return jsonify({"ok": True})


@app.route("/api/listings/<listing_id>/sold", methods=["POST"])
def sold(listing_id):
    db = Database(DB_PATH)
    db.set_manual_status(listing_id, "SOLD")
    db.close()
    return jsonify({"ok": True})


@app.route("/api/listings/<listing_id>/restore", methods=["POST"])
def restore(listing_id):
    db = Database(DB_PATH)
    db.set_manual_status(listing_id, "ACTIVE")
    db.close()
    return jsonify({"ok": True})


@app.route("/api/listings/<listing_id>/favorite", methods=["POST"])
def favorite(listing_id):
    db = Database(DB_PATH)
    try:
        new_value = db.toggle_favorite(listing_id)
    except ValueError:
        db.close()
        return jsonify({"error": "listing not found"}), 404
    db.close()
    return jsonify({"ok": True, "is_favorite": new_value})


@app.route("/api/listings/<listing_id>/specs", methods=["POST"])
def update_specs(listing_id):
    data = request.get_json(force=True, silent=True) or {}
    db = Database(DB_PATH)
    score_result = apply_spec_correction(db, scorer, listing_id, data, config=config)
    db.close()

    if score_result is None:
        return jsonify({"error": "listing not found or no editable fields given"}), 404

    return jsonify({"ok": True, "score_total": score_result["score_total"]})


def _find_app_mode_browser() -> Optional[str]:
    """Find a Chromium-based browser that supports --app= (a borderless
    window with no tabs/address bar — the closest a plain web page gets to
    looking like a real desktop program), checked in the order a Mac user
    is likely to have them installed."""
    candidates = [
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
        "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser",
        "/Applications/Chromium.app/Contents/MacOS/Chromium",
        shutil.which("google-chrome"),
        shutil.which("chromium"),
        shutil.which("chromium-browser"),
        shutil.which("microsoft-edge"),
    ]
    for path in candidates:
        if path and Path(path).exists():
            return path
    return None


def _open_app_window():
    time.sleep(0.8)  # give the Flask server a moment to start listening
    browser = _find_app_mode_browser()
    if browser:
        subprocess.Popen([browser, f"--app={URL}", "--window-size=1400,900"])
    else:
        print("Nessun browser Chromium-based trovato per la modalità app — apro nel browser predefinito.")
        webbrowser.open(URL)


if __name__ == "__main__":
    print("E-Bike Hunter — dashboard interattiva")
    print(f"Apro {URL} in una finestra app (Ctrl+C qui per fermare il server)")
    threading.Thread(target=_open_app_window, daemon=True).start()
    app.run(host=HOST, port=PORT, debug=False)
